require 'test_helper'

module ChildSafetySeatInspectionStationLocator
  class GetByStateTest < Minitest::Test
    def test_it_builds_url_as_expected
      expected_url = "https://webapi.nhtsa.gov/api/CSSIStation/state/MA?format=json"

      assert_equal expected_url, Nhtsa::ChildSafetySeatInspectionStationLocator::GetByState.new("MA").url
    end

    def test_it_adds_the_spanish_filter_to_url_when_specified
      expected_url = "https://webapi.nhtsa.gov/api/CSSIStation/state/MA/lang/spanish?format=json"

      assert_equal expected_url, Nhtsa::ChildSafetySeatInspectionStationLocator::GetByState.new("MA", {:spanish => true}).url
    end

    def test_it_adds_the_cpsweek_filter_to_url_when_specified
      expected_url = "https://webapi.nhtsa.gov/api/CSSIStation/state/MA/cpsweek?format=json"

      assert_equal expected_url, Nhtsa::ChildSafetySeatInspectionStationLocator::GetByState.new("MA", {:cpsweek => true}).url
    end

    def test_it_adds_the_spanish_and_cpsweek_filters_to_url_when_specified
      expected_url = "https://webapi.nhtsa.gov/api/CSSIStation/state/MA/cpsweek/lang/spanish?format=json"

      assert_equal expected_url, Nhtsa::ChildSafetySeatInspectionStationLocator::GetByState.new("MA", {:spanish => true, :cpsweek => true}).url
    end

    def test_inspection_stations_returns_an_array_of_location_hashes
      expected_location_hashes = [
        {
          "ContactFirstName"=>"Miriam",
          "ContactLastName"=>"Silis",
          "Organization"=>"Ron Wood Family Resource Center",
          "AddressLine1"=>"2621 Northgate Lane, Suite 62",
          "City"=>"Carson City",
          "State"=>"NV",
          "Zip"=>"89706",
          "Phone1"=>"775-884-2269",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1265734200000-0500)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Additional contact: Holly Brown. English/Spanish assistance available.\nTechnicians are Special Needs certified.\n",
          "CountiesServed"=>"All",
          "OperationHours"=>"Monday - Thursday, 8:00 am - 4:30 pm;\nFriday, 8:00 am -Noon. \nFor inspections, drop-ins are encouraged. For installations, please schedule an appointment.",
          "LocationLatitude"=>39.1838,
          "LocationLongitude"=>-119.766
        },
        {
          "ContactFirstName"=>"Jennifer",
          "ContactLastName"=>"Cleppe",
          "Organization"=>"Central Lyon County Fire Protection District",
          "AddressLine1"=>"231 Corral Drive",
          "City"=>"Dayton",
          "State"=>"NV",
          "Zip"=>"89403",
          "Phone1"=>"775-246-6209",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1308844921000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Alternate Contact:  Ryan Johnson.\nEnglish/Spanish speaking assistance available.",
          "LocationLatitude"=>39.2712,
          "LocationLongitude"=>-119.573
        },
        {
          "ContactFirstName"=>"Cindi",
          "ContactLastName"=>"Canaday",
          "Organization"=>"Family Resource Centers of Northeastern Nevada",
          "AddressLine1"=>"331 7th Street",
          "City"=>"Elko",
          "State"=>"NV",
          "Zip"=>"89801",
          "Email"=>"ddfrcnen@wirelessbeehive.com",
          "Fax"=>"775-777-9102",
          "Phone1"=>"775-753-7352",
          "Phone2"=>"775-738-9420",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1220890920000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Alternate Contact:\nMaria Barajas at 775-738-9420.\nEnglish/Spanish speaking assistance available.  \n",
          "CountiesServed"=>"Elko",
          "OperationHours"=>"8:00 am - 4:00 pm ",
          "LocationLatitude"=>40.8336,
          "LocationLongitude"=>-115.761
        },
        {
          "ContactFirstName"=>"Steve",
          "ContactMiddleInitial"=>"D",
          "ContactLastName"=>"Tafoya",
          "Organization"=>"Banner Churchill Hospital",
          "AddressLine1"=>"801 E Williams Ave",
          "City"=>"Fallon",
          "State"=>"NV",
          "Zip"=>"89406",
          "Email"=>"steven.tafoya@bannerhealth.com",
          "Fax"=>"775-428-2575",
          "Phone1"=>"775-867-7917",
          "Phone2"=>"775-867-7911",
          "CPSWeekEventFlag"=>"No",
          "CPSWeekEventStartDate"=>"\/Date(1353042000000-0500)\/",
          "LastUpdatedDate"=>"\/Date(1353364269000-0500)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"English/Spanish \r\n\r\nCall for appointment",
          "OperationHours"=>"8 a.m. - 5 p.m.\r\nMonday - Sunday\r\nafter hours if needed",
          "LocationLatitude"=>39.4762,
          "LocationLongitude"=>-118.766
        },
        {
          "ContactFirstName"=>"Kasey",
          "ContactLastName"=>"Miller",
          "Organization"=>"North Lyon County Fire Protection District",
          "AddressLine1"=>"195 East Main Street",
          "City"=>"Fernley",
          "State"=>"NV",
          "Zip"=>"89408",
          "Phone1"=>"775-575-3310",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1308752190000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for an Appointment.",
          "LocationLatitude"=>39.6076,
          "LocationLongitude"=>-119.248
        },
        {
          "ContactFirstName"=>"Kathy",
          "ContactLastName"=>"Secrist",
          "Organization"=>"SEATS:  Safety Education and Training Services",
          "AddressLine1"=>"123 Invalid",
          "City"=>"Fernley",
          "State"=>"NV",
          "Zip"=>"89408",
          "Phone1"=>"775-232-7131",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1308846188000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for appointment.",
          "LocationLatitude"=>39.5763,
          "LocationLongitude"=>-119.182
        },
        {
          "ContactFirstName"=>"Jen",
          "ContactLastName"=>"Findlay",
          "Organization"=>"St. Rose Dominican Hospitals",
          "AddressLine1"=>"Family to Family Connection",
          "AddressLine2"=>"102 E. Lake Mead",
          "City"=>"Henderson",
          "State"=>"NV",
          "Zip"=>"89015",
          "Phone1"=>"702-568-9601",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1308845124000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"By Appointment.\nMonday - Friday:\n9:00 am - 4:30 pm.",
          "LocationLatitude"=>-18,
          "LocationLongitude"=>146.166
        },
        {
          "Organization"=>"St. Rose Dominican Hospitals",
          "AddressLine1"=>"100 N Green Valley Pkwy",
          "City"=>"Henderson",
          "State"=>"NV",
          "Zip"=>"89074",
          "Phone1"=>"702-616-4901",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1347578702000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Go to Barbara Greenspun Womens Care Center of Excellence,\r\nSuite 330",
          "OperationHours"=>"Call for an appointment.",
          "LocationLatitude"=>36.026,
          "LocationLongitude"=>-115.084
        },
        {
          "ContactFirstName"=>"Jeanne",
          "ContactLastName"=>"Cosgrove",
          "Organization"=>"Sunrise Hospital & Medical Center",
          "AddressLine1"=>"3186 S Maryland Pkwy",
          "City"=>"Las Vegas",
          "State"=>"NV",
          "Zip"=>"89169",
          "Phone1"=>"702-731-8666",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1347578759000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"English/Spanish assistance available.  \r\nTechnicians are Special Needs certified.",
          "CountiesServed"=>"Clark",
          "OperationHours"=>"Friday, 8:00 am -11:30 am",
          "LocationLatitude"=>36.1346,
          "LocationLongitude"=>-115.136
        },
        {
          "ContactFirstName"=>"Rose",
          "ContactLastName"=>"Gardner",
          "Organization"=>"Family Resource Center",
          "AddressLine1"=>"901 Rancho Ln",
          "AddressLine2"=>"Suite 180",
          "City"=>"Las Vegas",
          "State"=>"NV",
          "Zip"=>"89106",
          "Fax"=>"720-383-0187",
          "Phone1"=>"702-383-2229",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1423764712000-0500)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Lisa Pacheco, RN",
          "OperationHours"=>"By appointment 8-4:30 M-F",
          "LocationLatitude"=>36.1606,
          "LocationLongitude"=>-115.171
        },
        {
          "ContactFirstName"=>"Matthew",
          "ContactLastName"=>"Macguire",
          "Organization"=>"Desert Volkswagen",
          "AddressLine1"=>"6375 West Sahara Avenue",
          "City"=>"Las Vegas",
          "State"=>"NV",
          "Zip"=>"89146",
          "Email"=>"mattsale2006@yahoo.com",
          "Phone1"=>"702-942-4000",
          "Phone2"=>"702-336-3473",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1189004880000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Additional contacts: Matthew Norton, Kaipo Kaae",
          "OperationHours"=>"Call for appointment.",
          "LocationLatitude"=>36.144,
          "LocationLongitude"=>-115.231
        },
        {
          "ContactFirstName"=>"Jamie",
          "ContactLastName"=>"Perez-Cruz",
          "Organization"=>"East Valley Family Services",
          "AddressLine1"=>"1800 E. Sahara",
          "AddressLine2"=>"Suite 111",
          "City"=>"Las Vegas",
          "State"=>"NV",
          "Zip"=>"89104",
          "Email"=>"eastvfs@yahoo.com",
          "Phone1"=>"702-696-1554",
          "Phone2"=>"702-733-7144",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1330560169000-0500)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for appointment",
          "LocationLatitude"=>36.1447,
          "LocationLongitude"=>-115.125
        },
        {
          "ContactFirstName"=>"Jamie",
          "ContactLastName"=>"Perez-Cruz",
          "Organization"=>"East Valley Family Services",
          "AddressLine1"=>"1800 E. Sahara",
          "AddressLine2"=>"Suite 111",
          "City"=>"Las Vegas",
          "State"=>"NV",
          "Zip"=>"89104",
          "Email"=>"eastvfs@yahoo.com",
          "Fax"=>"720-733-6144",
          "Phone1"=>"702-696-1554",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1330560228000-0500)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for appointment",
          "LocationLatitude"=>36.1447,
          "LocationLongitude"=>-115.125
        },
        {
          "Organization"=>"Summerlin Hospital",
          "AddressLine1"=>"657 N. Town Center Drive",
          "City"=>"Las Vegas",
          "State"=>"NV",
          "Zip"=>"89114",
          "Phone1"=>"702-233-7103",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1252693920000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"For Car Seat Check event, call 702-233-7103.",
          "OperationHours"=>"10:00 am - 12:00 pm\nNo appointment necessary.",
          "LocationLatitude"=>36.1795,
          "LocationLongitude"=>-115.316
        },
        {
          "ContactFirstName"=>"Penny",
          "ContactLastName"=>"Blair",
          "ContactTitle"=>"Certified Passenger Safety Technician",
          "Organization"=>"University of Nevada Cooperative Extension ",
          "AddressLine1"=>"1897 N. Moapa Valley Boulevard",
          "City"=>"Logandale",
          "State"=>"NV",
          "Zip"=>"89021",
          "Email"=>"blairp@unce.unv.edu",
          "Fax"=>"702-397-8301",
          "Phone1"=>"702-397-2604, Ext. 3",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1260808380000-0500)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"English/Spanish speaking assistance available.",
          "CountiesServed"=>"East Clark County",
          "OperationHours"=>"By appointment only",
          "LocationLatitude"=>36.5751,
          "LocationLongitude"=>-114.465
        },
        {
          "ContactFirstName"=>"Sheila",
          "ContactLastName"=>"Reitz",
          "Organization"=>"Pershing County Sheriff's Office",
          "AddressLine1"=>"395 9th St",
          "City"=>"Lovelock",
          "State"=>"NV",
          "Zip"=>"89419",
          "Phone1"=>"775-273-5111",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1361910738000-0500)\/",
          "MobileStationFlag"=>"No",
          "LocationLatitude"=>40.1795,
          "LocationLongitude"=>-118.476
        },
        {
          "ContactFirstName"=>"Sheila",
          "ContactLastName"=>"Reitz",
          "Organization"=>"Pershing County Sheriff's Office",
          "AddressLine1"=>"395 9th St",
          "City"=>"Lovelock",
          "State"=>"NV",
          "Zip"=>"89419",
          "Phone1"=>"775-273-5111",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1364335189000-0400)\/",
          "MobileStationFlag"=>"No",
          "LocationLatitude"=>40.1795,
          "LocationLongitude"=>-118.476
        },
        {
          "ContactFirstName"=>"Penny",
          "ContactLastName"=>"Blair",
          "Organization"=>"University of Nevada Cooperative Extension",
          "AddressLine1"=>"355 W. Mesquite Boulevard",
          "AddressLine2"=>"B-50",
          "City"=>"Mesquite",
          "State"=>"NV",
          "Zip"=>"89027",
          "Email"=>"blairp@unce.unv.edu",
          "Fax"=>"702-397-8301",
          "Phone1"=>"702-346-7215, Ext. 3",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1260829500000-0500)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"English/Spanish assistance available.",
          "CountiesServed"=>"East Clark County",
          "OperationHours"=>"By appointment only.",
          "LocationLatitude"=>36.8045,
          "LocationLongitude"=>-114.074
        },
        {
          "ContactFirstName"=>"Roberta",
          "ContactLastName"=>"Franco",
          "Organization"=>"Salvation Army",
          "AddressLine1"=>"355 W. Mesquite Boulevard",
          "AddressLine2"=>"B-50",
          "City"=>"Mesquite",
          "State"=>"NV",
          "Zip"=>"89027",
          "Phone1"=>"702-345-5116",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1193697720000-0400)\/",
          "MobileStationFlag"=>"No",
          "CountiesServed"=>"Clark",
          "OperationHours"=>"Monday - Friday",
          "LocationLatitude"=>36.8045,
          "LocationLongitude"=>-114.074
        },
        {
          "ContactFirstName"=>"Kim",
          "ContactLastName"=>"O Hare",
          "Organization"=>"Douglas County Sheriffs Office",
          "AddressLine1"=>"625 8th Street",
          "City"=>"Minden",
          "State"=>"NV",
          "Zip"=>"89423",
          "Phone1"=>"775-782-9945",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1301670264000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Alternate Contact:  Robbie Thorson.",
          "OperationHours"=>"By Appointment.",
          "LocationLatitude"=>38.956,
          "LocationLongitude"=>-119.767
        },
        {
          "Organization"=>"Olive Crest Family Resource Center, Family to Family Connection",
          "AddressLine1"=>"3825 W Cheyenne Ave",
          "City"=>"North Las Vegas",
          "State"=>"NV",
          "Zip"=>"89032",
          "Phone1"=>"702-685-3459",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1347578614000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Go to Suite 604",
          "OperationHours"=>"Call for an appointment.",
          "LocationLatitude"=>36.2167,
          "LocationLongitude"=>-115.19
        },
        {
          "ContactFirstName"=>"Stacy",
          "ContactLastName"=>"Smith",
          "Organization"=>"Nye Communities Coalition",
          "AddressLine1"=>"1020 W Wilson Rd",
          "City"=>"Pahrump",
          "State"=>"NV",
          "Zip"=>"89048",
          "Phone1"=>"775 727 9970 x228",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1364335253000-0400)\/",
          "MobileStationFlag"=>"No",
          "LocationLatitude"=>36.2127,
          "LocationLongitude"=>-116.033
        },
        {
          "ContactFirstName"=>"John",
          "ContactMiddleInitial"=>"E",
          "ContactLastName"=>"Carl",
          "Organization"=>"Northern Nevada Fitting Station",
          "AddressLine1"=>"595 Bell Street",
          "City"=>"Reno",
          "State"=>"NV",
          "Zip"=>"89503",
          "Email"=>"jcarl@remsa-cf.com",
          "Fax"=>"775-858-5735",
          "Phone1"=>"775-815-0981",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1303435424000-0400)\/",
          "MobileStationFlag"=>"No",
          "Note"=>"Technician is Special Needs-Certified.",
          "CountiesServed"=>"Northern Nevada",
          "OperationHours"=>"Monday-Friday\n8:00 - 5:00;\nSpanish-speaking assistance on Monday and Tuesday afternoons.",
          "LocationLatitude"=>39.5309,
          "LocationLongitude"=>-119.823
        },
        {
          "ContactFirstName"=>"Melissa",
          "ContactLastName"=>"Mansfield",
          "Organization"=>"AAA",
          "AddressLine1"=>"6795 S Virginia St",
          "City"=>"Reno",
          "State"=>"NV",
          "Zip"=>"89511",
          "Phone1"=>"(775) 326-2012",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1387210640000-0500)\/",
          "MobileStationFlag"=>"No",
          "LocationLatitude"=>39.4643,
          "LocationLongitude"=>-119.784
        },
        {
          "Organization"=>"Canyon Elementary School",
          "AddressLine1"=>"1492 E. 1240 S.",
          "City"=>"Spanish Fork",
          "State"=>"NV",
          "Zip"=>"84660",
          "Phone1"=>"000-000-0000",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1252693980000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"5:30 pm - 7:30 pm",
          "LocationLatitude"=>39.3565,
          "LocationLongitude"=>-116.655
        },
        {
          "ContactFirstName"=>"Marci",
          "ContactLastName"=>"Burke",
          "Organization"=>"SEATS:  Safety Education and Training Services",
          "AddressLine1"=>"123 Invalid",
          "City"=>"Sparks",
          "State"=>"NV",
          "Zip"=>"89434",
          "Phone1"=>"775-690-0700",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1308846294000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for an appointment.",
          "LocationLatitude"=>39.5453,
          "LocationLongitude"=>-119.649
        },
        {
          "ContactFirstName"=>"Allison",
          "ContactLastName"=>"Crookston",
          "Organization"=>"AAA",
          "AddressLine1"=>"4731 Galleria Pkwy",
          "AddressLine2"=>"Suite 105",
          "City"=>"Sparks",
          "State"=>"NV",
          "Zip"=>"89436",
          "Phone1"=>"775-356-3011",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1356030394000-0500)\/",
          "MobileStationFlag"=>"No",
          "CountiesServed"=>"All",
          "OperationHours"=>"By appointment only.",
          "LocationLatitude"=>39.5773,
          "LocationLongitude"=>-119.74
        },
        {
          "ContactFirstName"=>"Gary",
          "ContactLastName"=>"Corona",
          "Organization"=>"West Wendover Fire Department",
          "AddressLine1"=>"935 W. Wendover Boulevard",
          "City"=>"West Wendover",
          "State"=>"NV",
          "Zip"=>"89883",
          "Fax"=>"775-664-3599",
          "Phone1"=>"775-664-2274 (KISS)",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1189004880000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for appointment.",
          "LocationLatitude"=>40.738,
          "LocationLongitude"=>-114.061
        },
        {
          "ContactFirstName"=>"Debbie",
          "ContactLastName"=>"Whittaker",
          "ContactTitle"=>"AED Program Manager",
          "Organization"=>"Humboldt General Hospital",
          "AddressLine1"=>"Debbie Whittaker",
          "AddressLine2"=>"118 E. Haskell Street",
          "City"=>"Winnemucca",
          "State"=>"NV",
          "Zip"=>"89445",
          "Email"=>"aed@hghospital.ws",
          "Phone1"=>"775-623-5222, X-263",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1294247645000-0500)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for an appointment.",
          "LocationLatitude"=>41.2122,
          "LocationLongitude"=>-118.139
        },
        {
          "ContactFirstName"=>"Evelyn",
          "ContactLastName"=>"Dryer",
          "Organization"=>"Yerington Paiute Tribe",
          "AddressLine1"=>"171 Campbell Ln",
          "City"=>"Yerington",
          "State"=>"NV",
          "Zip"=>"89447",
          "Phone1"=>"(775) 463-7705",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1364334871000-0400)\/",
          "MobileStationFlag"=>"No",
          "LocationLatitude"=>39.0698,
          "LocationLongitude"=>-119.209
        },
        {
          "Organization"=>"Yerington/Mason Valley Fire Protection District",
          "AddressLine1"=>"118 S. Main Street",
          "City"=>"Yerington",
          "State"=>"NV",
          "Zip"=>"89447",
          "Fax"=>"775-463-6537",
          "Phone1"=>"775-463-2261",
          "CPSWeekEventFlag"=>"No",
          "LastUpdatedDate"=>"\/Date(1189004880000-0400)\/",
          "MobileStationFlag"=>"No",
          "OperationHours"=>"Call for appointment",
          "LocationLatitude"=>38.9851,
          "LocationLongitude"=>-119.163
        }
      ]

      assert_equal expected_location_hashes, Nhtsa::ChildSafetySeatInspectionStationLocator::GetByState.new("NV").inspection_stations
    end
  end
end
