require 'test_helper'

class RecallsTest < Minitest::Test

  def test_it_builds_url_as_expected
    expected_url = "https://webapi.nhtsa.gov/api/Recalls/vehicle/1998/Mitsubishi/Galant?format=json"

    assert_equal expected_url, Nhtsa::Recalls::Recalls.new(1998, "Mitsubishi", "Galant").url
  end

  def test_ratings_should_return_an_array_of_recalls
    recalls_array = [
      {
        "Manufacturer"=>"MITSUBISHI AMERICA",
        "NHTSACampaignNumber"=>"00V421001",
        "NHTSAActionNumber"=>"RQ00015",
        "ReportReceivedDate"=>"/Date(977115600000-0500)/",
        "Component"=>"SUSPENSION:FRONT:CONTROL ARM:LOWER BALL JOINT",
        "Summary"=>"VEHICLE DESCRIPTION:  PASSENGER VEHICLES.  IF THE RUBBER BOOTS ON THE LOWER LATERAL ARM BALL JOINTS OF THE FRONT SUSPENSION WERE DAMAGED DURING ASSEMBLY, DIRT AND WATER CAN INTRUDE.  ALSO, MMC HAS ADDED THE POTENTIAL OF LEAKING MOISTURE, WHICH CAN CAUSE THE BALL STUD TO CORRODE.",
        "Conequence"=>"THIS CONDITION COULD CAUSE THE LOWER LATERAL ARM BALL JOINT TO SEPARATE, INCREASING THE RISK OF A VEHICLE CRASH.  THIS CAMPAIGN SUPERCEDES MMC'S PREVIOUS SAFETY RECALL CAMPAIGN, SEE 99V-066.",
        "Remedy"=>"DEALERS WILL INSPECT THE LOWER LATERAL ARM BALL JOINT FOR WEAR.  BALL JOINTS THAT EXHIBIT WEAR BEYOND THE ESTABLISHED TOLERANCE WILL BE REPLACED WITH NEWLY DESIGNED LATERAL ARM BALL JOINTS.  BALL JOINTS THAT ARE WITHIN THE ESTABLISHED TOLERANCE WILL BE CLEANED AND A SPECIAL SEALANT WILL BE APPLIED TO PREVENT INTRUSION OF MOISTURE.",
        "Notes"=>"OWNER NOTIFICATION WILL BE CONDUCTED IN PHASES.  THE FIRST PHASE BEGAN APRIL 2, 2001, AND THE FINAL PHASE WILL BE COMPLETED ON SEPTEMBER 3, 2001.     OWNERS WHO TAKE THEIR VEHICLES TO AN AUTHORIZED DEALER ON AN AGREED UPON SERVICE DATE AND DO NOT RECEIVE THE FREE REMEDY WITHIN A REASONABLE TIME SHOULD CONTACT MITSUBISHI AMERICA AT 1-888-MITSU-2001 (1-888-648-7820).    ALSO CONTACT THE NATIONAL HIGHWAY TRAFFIC SAFETY ADMINISTRATION'S AUTO SAFETY HOTLINE AT 1-888-DASH-2-DOT (1-888-327-4236).",
        "ModelYear"=>"1998",
        "Make"=>"MITSUBISHI",
        "Model"=>"GALANT"
      },
      {
        "Manufacturer"=>"AIRTEX PRODUCTS",
        "NHTSACampaignNumber"=>"07E055000",
        "ReportReceivedDate"=>"/Date(1185422400000-0400)/",
        "Component"=>"FUEL SYSTEM, GASOLINE:DELIVERY:FUEL PUMP",
        "Summary"=>"CERTAIN AIRTEX FUEL PUMP MODULE ASSEMBLIES, P/N E7081H, SOLD FOR USE AS REPLACEMENT EQUIPMENT FOR THE VEHICLES LISTED ABOVE.  THE WALL OF THE FLARED FITTING OF THE FUEL PUMP IS NOT THICK ENOUGH TO PREVENT THE MATING THREADED FITTINGS FROM BOTTOMING OUT BEFORE AN ADEQUATE SEAL IS ACHIEVED.  THIS CONDITION MAY RESULT IN LEAKAGE OF FUEL AT THE CONNECTION OF THE VEHICLE FUEL LINE AND THE FUEL PUMP MODULE ASSEMBLY. ",
        "Conequence"=>"IN THE PRESENCE OF AN IGNITION SOURCE, A FUEL LEAK COULD RESULT IN A FIRE.",
        "Remedy"=>"AIRTEX WILL NOTIFY OWNERS AND REPLACE THE FUEL PUMPS FREE OF CHARGE.  THE RECALL IS EXPECTED TO BEGIN DURING JULY 2007.  OWNERS CAN CONTACT AIRTEX AUTOMOTIVE AT 800-880-3056.",
        "Notes"=>"AIRTEX RECALL NO. FP072007-1.  THIS RECALL ONLY PERTAINS TO AFTERMARKET REPLACEMENT EQUIPMENT AND HAS NO RELATION TO ANY ORIGINAL EQUIPMENT INSTALLED ON VEHICLES MANUFACTURED BY DAIMLERCHRYSLER OR MITSUBISHI.  CUSTOMERS MAY CONTACT THE NATIONAL HIGHWAY TRAFFIC SAFETY ADMINISTRATION'S VEHICLE SAFETY HOTLINE AT 1-888-327-4236 (TTY: 1-800-424-9153); OR GO TO HTTP://WWW.SAFERCAR.GOV.\r
",
        "ModelYear"=>"1998",
        "Make"=>"MITSUBISHI",
        "Model"=>"GALANT"
      }
    ]

    assert_equal recalls_array, Nhtsa::Recalls::Recalls.new(1998, "Mitsubishi", "Galant").recalls
  end

end
